package modelo;
// Generated 02-jun-2025 18:01:21 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Comentario generated by hbm2java
 */
public class Comentario  implements java.io.Serializable {


     private Integer id;
     private Publicacion publicacion;
     private Usuario usuario;
     private String contenido;
     private Date fechaComentario;

    public Comentario() {
    }

    public Comentario(Publicacion publicacion, Usuario usuario, String contenido, Date fechaComentario) {
       this.publicacion = publicacion;
       this.usuario = usuario;
       this.contenido = contenido;
       this.fechaComentario = fechaComentario;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Publicacion getPublicacion() {
        return this.publicacion;
    }
    
    public void setPublicacion(Publicacion publicacion) {
        this.publicacion = publicacion;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getContenido() {
        return this.contenido;
    }
    
    public void setContenido(String contenido) {
        this.contenido = contenido;
    }
    public Date getFechaComentario() {
        return this.fechaComentario;
    }
    
    public void setFechaComentario(Date fechaComentario) {
        this.fechaComentario = fechaComentario;
    }




}


