package modelo;
// Generated 02-jun-2025 18:01:21 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Evento generated by hbm2java
 */
public class Evento  implements java.io.Serializable {


     private Integer id;
     private Organizador organizador;
     private String titulo;
     private String descripcion;
     private String ubicacion;
     private Date fechaInicio;
     private Date fechaFin;
     private Integer plazas;
     private Set solicitudVoluntariados = new HashSet(0);
     private Set inscripcions = new HashSet(0);

    public Evento() {
    }

    public Evento(Organizador organizador, String titulo, String descripcion, String ubicacion, Date fechaInicio, Date fechaFin, Integer plazas, Set solicitudVoluntariados, Set inscripcions) {
       this.organizador = organizador;
       this.titulo = titulo;
       this.descripcion = descripcion;
       this.ubicacion = ubicacion;
       this.fechaInicio = fechaInicio;
       this.fechaFin = fechaFin;
       this.plazas = plazas;
       this.solicitudVoluntariados = solicitudVoluntariados;
       this.inscripcions = inscripcions;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Organizador getOrganizador() {
        return this.organizador;
    }
    
    public void setOrganizador(Organizador organizador) {
        this.organizador = organizador;
    }
    public String getTitulo() {
        return this.titulo;
    }
    
    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getUbicacion() {
        return this.ubicacion;
    }
    
    public void setUbicacion(String ubicacion) {
        this.ubicacion = ubicacion;
    }
    public Date getFechaInicio() {
        return this.fechaInicio;
    }
    
    public void setFechaInicio(Date fechaInicio) {
        this.fechaInicio = fechaInicio;
    }
    public Date getFechaFin() {
        return this.fechaFin;
    }
    
    public void setFechaFin(Date fechaFin) {
        this.fechaFin = fechaFin;
    }
    public Integer getPlazas() {
        return this.plazas;
    }
    
    public void setPlazas(Integer plazas) {
        this.plazas = plazas;
    }
    public Set getSolicitudVoluntariados() {
        return this.solicitudVoluntariados;
    }
    
    public void setSolicitudVoluntariados(Set solicitudVoluntariados) {
        this.solicitudVoluntariados = solicitudVoluntariados;
    }
    public Set getInscripcions() {
        return this.inscripcions;
    }
    
    public void setInscripcions(Set inscripcions) {
        this.inscripcions = inscripcions;
    }




}


