package modelo;
// Generated 02-jun-2025 18:01:21 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Notificacion generated by hbm2java
 */
public class Notificacion  implements java.io.Serializable {


     private Integer id;
     private Usuario usuario;
     private String mensaje;
     private Boolean leida;
     private Date fechaEnvio;

    public Notificacion() {
    }

    public Notificacion(Usuario usuario, String mensaje, Boolean leida, Date fechaEnvio) {
       this.usuario = usuario;
       this.mensaje = mensaje;
       this.leida = leida;
       this.fechaEnvio = fechaEnvio;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getMensaje() {
        return this.mensaje;
    }
    
    public void setMensaje(String mensaje) {
        this.mensaje = mensaje;
    }
    public Boolean getLeida() {
        return this.leida;
    }
    
    public void setLeida(Boolean leida) {
        this.leida = leida;
    }
    public Date getFechaEnvio() {
        return this.fechaEnvio;
    }
    
    public void setFechaEnvio(Date fechaEnvio) {
        this.fechaEnvio = fechaEnvio;
    }




}


