package modelo;
// Generated 02-jun-2025 18:01:21 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Organizador generated by hbm2java
 */
public class Organizador  implements java.io.Serializable {


     private Integer id;
     private Usuario usuario;
     private Set eventos = new HashSet(0);

    public Organizador() {
    }

    public Organizador(Usuario usuario, String nombreOrganizacion, String descripcion, Set eventos) {
       this.usuario = usuario;
       this.eventos = eventos;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    
    public Set getEventos() {
        return this.eventos;
    }
    
    public void setEventos(Set eventos) {
        this.eventos = eventos;
    }




}


