package modelo;
// Generated 02-jun-2025 18:01:21 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Publicacion generated by hbm2java
 */
public class Publicacion  implements java.io.Serializable {


     private Integer id;
     private Usuario usuario;
     private String titulo;
     private String contenido;
     private Date fechaPublicacion;
     private Set comentarios = new HashSet(0);

    public Publicacion() {
    }

    public Publicacion(Usuario usuario, String titulo, String contenido, Date fechaPublicacion, Set comentarios) {
       this.usuario = usuario;
       this.titulo = titulo;
       this.contenido = contenido;
       this.fechaPublicacion = fechaPublicacion;
       this.comentarios = comentarios;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getTitulo() {
        return this.titulo;
    }
    
    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }
    public String getContenido() {
        return this.contenido;
    }
    
    public void setContenido(String contenido) {
        this.contenido = contenido;
    }
    public Date getFechaPublicacion() {
        return this.fechaPublicacion;
    }
    
    public void setFechaPublicacion(Date fechaPublicacion) {
        this.fechaPublicacion = fechaPublicacion;
    }
    public Set getComentarios() {
        return this.comentarios;
    }
    
    public void setComentarios(Set comentarios) {
        this.comentarios = comentarios;
    }




}


