package modelo;
// Generated 02-jun-2025 18:01:21 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * SolicitudVoluntariado generated by hbm2java
 */
public class SolicitudVoluntariado  implements java.io.Serializable {


     private Integer id;
     private Evento evento;
     private Usuario usuario;
     private String estado;
     private Date fechaSolicitud;
     private Set tareaVoluntarios = new HashSet(0);

    public SolicitudVoluntariado() {
    }

    public SolicitudVoluntariado(Evento evento, Usuario usuario, String estado, Date fechaSolicitud, Set tareaVoluntarios) {
       this.evento = evento;
       this.usuario = usuario;
       this.estado = estado;
       this.fechaSolicitud = fechaSolicitud;
       this.tareaVoluntarios = tareaVoluntarios;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Evento getEvento() {
        return this.evento;
    }
    
    public void setEvento(Evento evento) {
        this.evento = evento;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Date getFechaSolicitud() {
        return this.fechaSolicitud;
    }
    
    public void setFechaSolicitud(Date fechaSolicitud) {
        this.fechaSolicitud = fechaSolicitud;
    }
    public Set getTareaVoluntarios() {
        return this.tareaVoluntarios;
    }
    
    public void setTareaVoluntarios(Set tareaVoluntarios) {
        this.tareaVoluntarios = tareaVoluntarios;
    }




}


