package modelo;
// Generated 02-jun-2025 18:01:21 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * TareaVoluntario generated by hbm2java
 */
public class TareaVoluntario  implements java.io.Serializable {


     private Integer id;
     private SolicitudVoluntariado solicitudVoluntariado;
     private String descripcion;
     private Date horaInicio;
     private Date horaFin;

    public TareaVoluntario() {
    }

    public TareaVoluntario(SolicitudVoluntariado solicitudVoluntariado, String descripcion, Date horaInicio, Date horaFin) {
       this.solicitudVoluntariado = solicitudVoluntariado;
       this.descripcion = descripcion;
       this.horaInicio = horaInicio;
       this.horaFin = horaFin;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public SolicitudVoluntariado getSolicitudVoluntariado() {
        return this.solicitudVoluntariado;
    }
    
    public void setSolicitudVoluntariado(SolicitudVoluntariado solicitudVoluntariado) {
        this.solicitudVoluntariado = solicitudVoluntariado;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Date getHoraInicio() {
        return this.horaInicio;
    }
    
    public void setHoraInicio(Date horaInicio) {
        this.horaInicio = horaInicio;
    }
    public Date getHoraFin() {
        return this.horaFin;
    }
    
    public void setHoraFin(Date horaFin) {
        this.horaFin = horaFin;
    }




}


