package modelo;
// Generated 02-jun-2025 18:01:21 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private String email;
     private String contrasena;
     private String tipo;
     private Date fechaRegistro;
     private Set notificacions = new HashSet(0);
     private Set solicitudVoluntariados = new HashSet(0);
     private Set comentarios = new HashSet(0);
     private Set inscripcions = new HashSet(0);
     private Set publicacions = new HashSet(0);
     private Set organizadors = new HashSet(0);

    public Usuario() {
    }

    public Usuario(String nombre, String email, String contrasena, String tipo, Date fechaRegistro, Set notificacions, Set solicitudVoluntariados, Set comentarios, Set inscripcions, Set publicacions, Set organizadors) {
       this.nombre = nombre;
       this.email = email;
       this.contrasena = contrasena;
       this.tipo = tipo;
       this.fechaRegistro = fechaRegistro;
       this.notificacions = notificacions;
       this.solicitudVoluntariados = solicitudVoluntariados;
       this.comentarios = comentarios;
       this.inscripcions = inscripcions;
       this.publicacions = publicacions;
       this.organizadors = organizadors;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getContrasena() {
        return this.contrasena;
    }
    
    public void setContrasena(String contrasena) {
        this.contrasena = contrasena;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public Date getFechaRegistro() {
        return this.fechaRegistro;
    }
    
    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }
    public Set getNotificacions() {
        return this.notificacions;
    }
    
    public void setNotificacions(Set notificacions) {
        this.notificacions = notificacions;
    }
    public Set getSolicitudVoluntariados() {
        return this.solicitudVoluntariados;
    }
    
    public void setSolicitudVoluntariados(Set solicitudVoluntariados) {
        this.solicitudVoluntariados = solicitudVoluntariados;
    }
    public Set getComentarios() {
        return this.comentarios;
    }
    
    public void setComentarios(Set comentarios) {
        this.comentarios = comentarios;
    }
    public Set getInscripcions() {
        return this.inscripcions;
    }
    
    public void setInscripcions(Set inscripcions) {
        this.inscripcions = inscripcions;
    }
    public Set getPublicacions() {
        return this.publicacions;
    }
    
    public void setPublicacions(Set publicacions) {
        this.publicacions = publicacions;
    }
    public Set getOrganizadors() {
        return this.organizadors;
    }
    
    public void setOrganizadors(Set organizadors) {
        this.organizadors = organizadors;
    }




}


